# -*- coding: utf-8 -*-
"""Parquet-transform.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12-TjRdo1qLqWcmTn602czKEh3gv5QtWx
"""

import json
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, from_json, lit, from_unixtime, to_date, year, month
from pyspark.sql.types import StructType, StructField, StringType, ArrayType, DoubleType, IntegerType, MapType

def create_spark_session(app_name="RecommenderELT"):
    spark = SparkSession.builder \
        .appName(app_name) \
        .config("spark.driver.memory", "4g") \
        .getOrCreate()
    return spark

def load_meta_data(spark, file_path):
    schema = StructType([
        StructField("main_category", StringType(), True),
        StructField("title", StringType(), True),
        StructField("average_rating", DoubleType(), True),
        StructField("rating_number", IntegerType(), True),
        StructField("features", ArrayType(StringType()), True),
        StructField("description", ArrayType(StringType()), True),
        StructField("price", StringType(), True),
        StructField("images", ArrayType(MapType(StringType(), StringType())), True),
        StructField("videos", ArrayType(StringType()), True),
        StructField("store", StringType(), True),
        StructField("categories", ArrayType(StringType()), True),
        StructField("details", MapType(StringType(), StringType()), True),
        StructField("parent_asin", StringType(), True),
        StructField("bought_together", StringType(), True)
    ])
    df_raw = spark.read.text(file_path)
    df_meta = df_raw.select(from_json(col("value"), schema).alias("json")).select("json.*")
    return df_meta

def load_ratings_data(spark, file_path):
    return spark.read.json(file_path)

def save_meta_as_parquet(df, out_path):
    """
    Save meta DataFrame as Parquet to HDFS (no partition)
    """
    df.write.mode("overwrite").parquet(out_path)

def save_ratings_partitioned(df, timestamp_col, out_path):
    """
    Save ratings DataFrame as Parquet partitioned by year/month (from timestamp in ms)
    """
    # convert timestamp milliseconds → date
    df = df.withColumn(
        "event_date",
        to_date(from_unixtime(col(timestamp_col) / 1000))
    )
    # extract year and month
    df = df.withColumn("year", year(col("event_date")))
    df = df.withColumn("month", month(col("event_date")))

    # save partitioned by year/month
    df.write.partitionBy("year", "month") \
        .mode("overwrite") \
        .parquet(out_path)

# ================== MAIN =====================
spark = create_spark_session()

# Đường dẫn HDFS
meta_path_hdfs = "hdfs:///DATALAKE/MyData/amazon-reviews-2023/raw/meta_categories/meta_Beauty_and_Personal_Care.jsonl"
ratings_path_hdfs = "hdfs:///DATALAKE/MyData/amazon-reviews-2023/raw/review_categories/Beauty_and_Personal_Care.jsonl"

# Đọc
df_meta = load_meta_data(spark, meta_path_hdfs)
df_ratings = load_ratings_data(spark, ratings_path_hdfs)

# Lưu meta (không partition)
save_meta_as_parquet(df_meta,
    "hdfs:///DATALAKE/MyData/meta_Beauty_and_Personal_Care")

# Lưu ratings (partition theo year/month)
save_ratings_partitioned(df_ratings, "timestamp",
    "hdfs:///DATALAKE/MyData/Beauty_and_Personal_Care")

spark.stop()